services:
  bookstack:
    image: "docker.io/willdockerhub/bookstack:v2.12"
    container_name: bookstack
    command: sleep infinity
    ports:
      - "8181:8181"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - bookstack

  db:
    image: "mysql:8.4.1"
    container_name: bookstack_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "bookstack123"
      MYSQL_DATABASE: "bookstack"
      MYSQL_USER: "bookstack"
      MYSQL_PASSWORD: "bookstack123"
    volumes:
      - "mysql-data:/var/lib/mysql"
    restart: unless-stopped
    networks:
      - bookstack

networks:
  bookstack:

volumes:
  mysql-data:
